version: '3'
services:
  guacamole-server:
    image: guacamole/guacamole
    container_name: guacamole-server
    ports:
      - '8080:8080'
    environment:
      - GUACD_HOSTNAME=guacd
      - MYSQL_HOSTNAME=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=guacamole_password
    depends_on:
      - guacd
      - mysql
  guacd:
    image: guacamole/guacd
    container_name: guacd
    restart: unless-stopped
    ports:
      - '4822:4822'
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=guacamole_password
      - MYSQL_ROOT_PASSWORD=guacamole_root_password
    volumes:
      - ./my-db:/var/lib/mysql
volumes:
  my-db:
